### ISSUE TITLE
기획 부실로 인한 여러 이슈

### ISSUE THREAD

**Issue by wlsh44** [TeamCrazyPerformance/TCP-Agenda#15]
## 기획 변경 안건

- 안건 리스트 받아오는 부분 페이징 처리를 하고싶어요..ㅎ 페북 같은 커서 기반 페이징 처리 생각하고 있습니다!
- 권한에 따른 API가 딱히 필요 없을 것 같은데 어떻게 생각하시나요? (notion에 있는 role 부분) 투표는 누구든 올릴 수 있게 하고 차라리 추후에 어드민 페이지를 추가하는게 더 좋을 것 같다는 생각을 했심다.
- 이미 투표가 진행 중인 안건에 대해서 수정을 할 수 있게 하는게 맞나에 대한 생각이 들었는데 어떻게 생각하시나요??

### 안건 리스트 받아오기

단순 리스트 -> 페이징 처리 (cursor-based)

- GET /agenda?page=0 (default=0)

body
```
{
  agendaList: [
      id: "1",
      title: "test",
      createdAt: "2023-03-01T22:59:59",
      closedAt: "2023-03-01T22:59:59",
      target: "재학생",
      votedMember: "1",
      isOpen: boolean,
  ],
  pageNumber = 0,
  hasNext = true
}
```

### 특정 안건 투표 취소하기

투표에 대한 id가 필요해서 주소 변경

- POST /agenda/:id/cancel -> DELETE /agenda/:agendaId/vote/:voteId

****

보시고 어떤지 말씀해주세요!

**Comment by usageness** [comment]
1. 페이징 처리
굿~
따로 안넘겨주면 0번 페이지 보여줘~

2. Role
이건 참여자/관리자 구분보다는 재학생만 투표할 수 있게 한 것 때문에 만든게 커서 유지해야 하지 않을까??

3. 투표 수정
정책적으로 수정을 막으면 개발하는 입장에서 편한건 맞는데 잘못 올리는 경우나 중간에 내용을 추가하는 경우가 많을 것 같음. 있어야하지 않을까?

**Comment by wlsh44** [comment]
> 이건 참여자/관리자 구분보다는 재학생만 투표할 수 있게 한 것 때문에 만든게 커서 유지해야 하지 않을까??

아아 그 기능은 유지하고, 감투 권한만 투표를 올릴 수 있게 하는 부분이 필요 없을 것 같다는 얘기었습니다!

<img width="394" alt="image" src="https://user-images.githubusercontent.com/49276666/222998531-b19d0b7a-bbeb-42e7-9a14-6f32a8d7a9d8.png">

이런 느낌으로 프런트에서는 권한 상관 없이 같은 페이지를 보여주는게 어떨까 싶어서요

> 정책적으로 수정을 막으면 개발하는 입장에서 편한건 맞는데 잘못 올리는 경우나 중간에 내용을 추가하는 경우가 많을 것 같음. 있어야하지 않을까?

제목이나 내용 수정은 괜찮은데 이미 투표가 된 상태에서 투표 리스트를 수정하는게 좀 이상하다고 느꼈어요
좀 이상한 예시이긴 한데, 찬반 투표를 올려서 찬성5/반대1 나왔는데 투표 리스트 내용을 수정해서 반대5/찬성1이 될 수도 있을 것 같다는 생각을 했어요..!
또 지금은 중복 투표만으로 기획을 하고 있는데 나중에 중복투표/단일투표 선택할 수 있게 기능을 추가하게 되면, 누군가 중복 투표를 한 상황에서 단일 투표로 수정하는 작업이 힘들 것 같아요

그래서 카톡 투표처럼 누군가 투표를 했으면 수정이 안 되고, 아무도 투표를 안 한 상태면 수정이 되게 하는거는 어떨까요?

**Comment by wlsh44** [comment]
API 수정 사항은 괜찮으신가용?

**Comment by usageness** [comment]
아하 Role부분 수정은 그렇게 해도 될거같다~

투표 선택지 추가정도까지는 허용하고, 나머지는 안되게 하는게 맞을듯 ㅎㅎ

API 수정은 괜찮음!

**Comment by wlsh44** [comment]
> 투표 선택지 추가정도까지는 허용하고, 나머지는 안되게 하는게 맞을듯 ㅎㅎ

넵 알겠습니다!

마지막으로 저번에 저희가 빼먹었는지 투표하는거 API에 reuqest body가 없어서 다음처럼 추가하려고 해요
```
POST /agenda/:id/vote

request body
{
  "selectList": [{"id": 1}, {"id": 3}]
}

response body
200 OK
```
보시고 바꿔야될 부분 있으면 말씀해주시구 문제 없어보이면 이슈 close 해주세요! 그러면 이대로 notion 수정하러 가겠습니다ㅏ 🫠

**Comment by usageness** [comment]
selectList 값 부분에 Id 필드가 필수로 필요한건가??

```json
"selectList": "[1, 3]"
```

처럼은 하면 안됨?? (몰라서 물어봄)

**Comment by usageness** [comment]
굿굿 ㅎㅎ 그대로 진행하면 될거같아~~!

**Comment by wlsh44** [comment]
> 투표 선택지 추가정도까지는 허용하고, 나머지는 안되게 하는게 맞을듯 ㅎㅎ

투표 수정 기능에서

**Comment by usageness** [comment]
> 그래서 진행 중인 투표는 그냥 선택지 추가 기능을 없애거나 차라리 투표 항목 추가 API를 새로 만드는게 더 나을 것 같은데 어떠신가요?

동의하는 부분! 카톡 투표도 보면 투표 항목 추가를 별개의 기능으로 받고 있던데 아마 이런 문제때문이 아니었을까 싶네요~

투표 항목 추가 API를 추가하는 쪽으로 하는게 좋아 보입니다!

**Comment by wlsh44** [comment]
넵 그럼 그 부분은 일단 배포 후 기능으로 넣어둘게요!
