### ISSUE TITLE
[BE] CI/CD 파이프라인 구축

### ISSUE THREAD

**Issue by wlsh44** [TeamCrazyPerformance/TCP-Agenda#35]
## 구현할 내용
- [x] git action pipeline 설정
  - [x] secrets 값들 설정
- [x] docker repository 생성
- [x] 동아리 서버 개발환경 세팅
  - [x] IP 주소 알아오기
  - [x] ~~docker 다운 및~~ compose 파일 생성
    - [x] nginx, blue-green 서비스 2개 포함
  - [x] deploy 스크립트 작성

**Comment by usageness** [comment]
젠킨스 해줘

**Comment by wlsh44** [comment]
넵 그럼 이제부터 main develop 말고는 브랜치 이름 앞에 backend/ prefix 붙이겠습니당
근데 혹시 dev 서버 필요해서 코맨트 달아주신건가요?

**Comment by usageness** [comment]
그럼 브랜치 네이밍은
`backend/feature/something`
이렇게 가져가는게 맞나요?
Dev서버 필요해서 코멘트 단건 아닙니다!
실서버에서 테스트 할거에요 ㅋㅋ

**Comment by usageness** [comment]
좋아요~
