### ISSUE TITLE
동아리 부원 현황 파일에 학번 기입 저조함

### ISSUE THREAD

**Issue by wise1ight** [TeamCrazyPerformance/TCP-Agenda#8]
학번 전체 8자리를 ID로 해서 로그인하는것으로 알고있는데
구드에서 동아리 부원 현황 파일에 재학생들 각자의 학번 기입이 저조함.

그대로 학번을 ID로 사용할 것인지(좀 더 기다릴 것인지) 다른방법 사용할 것인지 의견 남겨주세요.

**Comment by wlsh44** [comment]
일단 학번을 ID로 해서 구현하긴 했는데 확실히 다른 방법으로 바꿔야되나 고민이 되네요..

일단 공지 톡방에 올려보고 개발 전까지 기입률이 너무 적으면 방법을 바꾸는게 어떨까 싶어요.
원래 비번을 생일로 하려고 했는데 생일도 너무 적어서 비번을 뭘로 할지도 고민이 되네요ㅠ

**Comment by wise1ight** [comment]
언제까지 기다릴지 **기한을 정하고** 그때 다시 의논하는게 맞는것 같은데
다가오는 주모임에서 한번 더 리마인드를 하고 3/10까지 진전이 없으면 다른 방법을 의논해봅시다.

**Comment by wlsh44** [comment]
좋습니당 🙂
카톡방에도 꼭 올려주세요!

**Comment by wise1ight** [comment]
참여 독려와 EPIC 자료 만드는 겸사겸사해서 학번 받은것으로 극소수를 제외하고 재학생 학번 입력 완료.
